#!/bin/sh

IMAGE_ID=ab-ssh-tunnel

docker run \
	-d \
	-e 22 \
	-i \
	--link redis \
	--name ssh-tunnel \
	--net archivebot \
	--restart unless-stopped \
	-p 22:22 \
	-t \
	-v $HOME/state/ssh-tunnel/home/archivebot/.ssh:/home/archivebot/.ssh \
	-v $HOME/state/ssh-tunnel/etc/ssh:/etc/ssh \
	$IMAGE_ID \
	/usr/sbin/sshd -D
