#!/bin/sh

IMAGE_ID=06755221db33

docker run \
	-d \
	-e 22 \
	-i \
	--link redis \
	--name ssh-tunnel \
	--net archivebot \
	--restart unless-stopped \
	-p 22:22 \
	-t \
	-v $HOME/state-ssh-archivebot:/home/archivebot/.ssh \
	-v $HOME/state-ssh:/etc/ssh \
	$IMAGE_ID \
	/usr/sbin/sshd -D
